### ISSUE TITLE
Displaying video preview thumbnails not working

### ISSUE THREAD

**Issue by AlyChloe** [AlyChloe/funnystuff#1]
I keep getting a grey YouTube image and not the video preview themselves. @jglovier

**Comment by jglovier** [comment]
So I forked your repo and cloned it locally, and the first thing I noticed when I run it in browser is there are several JS errors. I would start with trying to debug these errors:

<img width="1280" alt="screen shot 2015-12-24 at 3 25 27 pm" src="https://cloud.githubusercontent.com/assets/1319791/11997759/24c827f2-aa53-11e5-9c41-ce0171be6c88.png">

Are you familiar with Chrome's devtools console? That's the first place I always check when something isn't working right on the front end.

**Comment by jglovier** [comment]
@AlyChloe did you get the issue resolved? Assuming you did because you've closed it, but hollar if you need any further help debugging!
